src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingAskerFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\Form;

/**
 * Handle Asker Dashboard Booking Form
 *
 */
class BookingAskerFormHandler extends BookingFormHandler
{
    /**
     * Save Booking.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2: Wrong Booking Status
     * -3: Refund error
     * -4: Unknown error
     */
    protected function onSuccess(Form $form)
    {
        $result = -4; //Unknown error

        /** @var Booking $booking */
        $booking = $form->getData();
        $message = $form->get("message")->getData();
        $this->threadManager->addReplyThread($booking, $message, $booking->getUser());
        //Cancel
        $type = $this->request->get('type');
        if (in_array($booking->getStatus(), Booking::$cancelableStatus)) {
            if ($type == 'cancel') {
                if ($this->bookingManager->cancel($booking)) {
                    $result = 1;
                } else {
                    $result = -3;
                }
            }
        } else {
            $result = -2;
        }

        return $result;
    }
}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Model\Manager\BookingManager;
use Cocorico\MessageBundle\Model\ThreadManager;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Handle Booking Form
 *
 */
abstract class BookingFormHandler
{
    /** @var Request $request */
    protected $request;
    /** @var BookingManager $bookingManager */
    protected $bookingManager;
    /** @var  ThreadManager $threadManager */
    protected $threadManager;
    /** @var  int */
    protected $expirationDelay;
    /** @var  int */
    protected $acceptationDelay;

    /**
     * @param RequestStack $requestStack
     */
    public function setRequest(RequestStack $requestStack)
    {
        $this->request = $requestStack->getCurrentRequest();;
    }

    /**
     * @param BookingManager $bookingManager
     */
    public function setBookingManager(BookingManager $bookingManager)
    {
        $this->bookingManager = $bookingManager;
    }

    /**
     * @param ThreadManager $threadManager
     */
    public function setThreadManager(ThreadManager $threadManager)
    {
        $this->threadManager = $threadManager;
    }

    /**
     * Process form
     *
     * @param $form
     *
     * @return int equal to :
     * 1: Success
     * 0: if form is not submitted:
     * -1: if form is not valid
     * -2: Wrong Booking Status
     *
     */
    public function process(Form $form)
    {
        $form->handleRequest($this->request);

        if ($form->isSubmitted() && $this->request->isMethod('POST')) {
            if ($form->isValid()) {
                $result = $this->onSuccess($form);
            } else {
                $result = -1;//form not valid
            }
        } else {
            $result = 0; //Not submitted
        }

        return $result;
    }

    /**
     * To override
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2:
     * -3:
     * -4: Unknown error
     */
    abstract protected function onSuccess(Form $form);


}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/BookingOffererFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\Form;

/**
 * Handle Offerer Dashboard Booking Form
 *
 */
class BookingOffererFormHandler extends BookingFormHandler
{
    /**
     * Save Booking.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     * -2: Wrong Booking Status
     * -3: Payin PreAuth error
     * -4: Unknown error
     */
    protected function onSuccess(Form $form)
    {
        $result = -4; //Unknown error

        /** @var Booking $booking */
        $booking = $form->getData();
        $message = $form->get("message")->getData();
        $this->threadManager->addReplyThread($booking, $message, $booking->getListing()->getUser());
        //Accept or refuse
        $type = $this->request->get('type');

        $canBeAcceptedOrRefused = $this->bookingManager->canBeAcceptedOrRefusedByOfferer($booking);
        if ($canBeAcceptedOrRefused) {
            if ($type == 'accept') {
                if ($this->bookingManager->pay($booking)) {
                    $result = 1;
                } else {
                    $result = -3;
                }
            } elseif ($type == 'refuse') {
                $this->bookingManager->refuse($booking);
                $result = 1;
            }
        } else {
            $result = -2;
        }

        return $result;
    }
}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/ListingAvailabilityFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Model\Manager\ListingAvailabilityManager;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Handle Listing Availability Form
 *
 */
abstract class ListingAvailabilityFormHandler
{
    /** @var Request $request */
    protected $request;
    /** @var ListingAvailabilityManager $listingAvailabilityManager */
    protected $listingAvailabilityManager;
    /** @var  EntityManager $entityManager */
    protected $entityManager;

    /**
     * @param RequestStack $requestStack
     */
    public function setRequest(RequestStack $requestStack)
    {
        $this->request = $requestStack->getCurrentRequest();;
    }

    /**
     * @param ListingAvailabilityManager $listingAvailabilityManager
     */
    public function setListingAvailabilityManager(ListingAvailabilityManager $listingAvailabilityManager)
    {
        $this->listingAvailabilityManager = $listingAvailabilityManager;
    }

    /**
     * @param EntityManager $entityManager
     */
    public function setEntityManager(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Process form
     *
     * @param $form
     *
     * @return int equal to :
     * 1: Success
     * 0: if form is not submitted:
     * -1: if form is not valid
     *
     */
    public function process(Form $form)
    {
        $form->handleRequest($this->request);

        if ($form->isSubmitted() && $this->request->isMethod('POST')) {
            if ($form->isValid()) {
                $result = $this->onSuccess($form);
            } else {
                $result = -1;//form not valid
            }
        } else {
            $result = 0; //Not submitted
        }

        return $result;
    }

    /**
     * To override
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     */
    abstract protected function onSuccess(Form $form);


}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/ListingAvailabilityPriceFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Listing;
use Symfony\Component\Form\Form;

/**
 * Handle Listing Availability Price Form
 *
 */
class ListingAvailabilityPriceFormHandler extends ListingAvailabilityFormHandler
{
    /**
     * Save Listing Availability Price.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     */
    protected function onSuccess(Form $form)
    {
        /** @var Listing $listing */
        $listing = $form->getData();

        //If mod_fcgi then add IPCCommTimeout, IPCConnectTimeout to Vhost
        //Else set_time_limit(120);ini_set('max_execution_time', 120);ini_set('memory_limit', '256M');

        $this->listingAvailabilityManager->saveAvailabilitiesPrices(
            $listing->getId(),
            $form->get('date_range')->getData(),
            $form->get('weekdays')->getData(),
            $form->has('time_ranges') ? $form->get('time_ranges')->getData() : array(),
            $form->get('price_custom')->getData(),
            false,
            false
        );

        $listing->setAvailabilitiesUpdatedAt(new \DateTime());
        $this->entityManager->persist($listing);
        $this->entityManager->flush();

        return 1;
    }
}

src/Cocorico/CoreBundle/Form/Handler/Dashboard/ListingAvailabilityStatusFormHandler.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cocorico\CoreBundle\Form\Handler\Dashboard;

use Cocorico\CoreBundle\Entity\Listing;
use Symfony\Component\Form\Form;

/**
 * Handle Listing Availability Status Form
 *
 */
class ListingAvailabilityStatusFormHandler extends ListingAvailabilityFormHandler
{
    /**
     * Save Listing Availability Status.
     *
     * @param Form $form
     *
     * @return int equal to :
     * 1: Success
     */
    protected function onSuccess(Form $form)
    {
        /** @var Listing $listing */
        $listing = $form->getData();
        $this->listingAvailabilityManager->saveAvailabilitiesStatus(
            $listing->getId(),
            $form->get('date_range')->getData(),
            $form->get('weekdays')->getData(),
            $form->has('time_ranges') ? $form->get('time_ranges')->getData() : array(),
            $form->get('status')->getData(),
            $listing->getPrice(),
            false,
            false
        );

        $listing->setAvailabilitiesUpdatedAt(new \DateTime());
        $this->entityManager->persist($listing);
        $this->entityManager->flush();

        return 1;
    }
}

src/Cocorico/CoreBundle/Form/Type/Dashboard/BookingEditType.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CoreBundle\Form\Type\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use JMS\TranslationBundle\Model\Message;
use JMS\TranslationBundle\Translation\TranslationContainerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\NotBlank;

class BookingEditType extends AbstractType implements TranslationContainerInterface
{
    public static $tacError = 'listing.form.tac.error';

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var Booking $booking */
        //$booking = $builder->getData();
        $builder
            ->add(
                "tac",
                "checkbox",
                array(
                    'label' => 'booking.form.tac',
                    'mapped' => false,
                    'constraints' => new IsTrue(
                        array(
                            "message" => self::$tacError
                        )
                    ),
                )
            )
            ->add(
                'message',
                'textarea',
                array(
                    'mapped' => false,
                    'label' => 'booking.form.message',
                    'required' => true,
                    'constraints' => new NotBlank(),
                )
            );

    }


    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Cocorico\CoreBundle\Entity\Booking',
                'csrf_token_id' => 'booking_edit',
                'translation_domain' => 'cocorico_booking',
                'cascade_validation' => true,
//                'validation_groups' => array('edit', 'default'),
            )
        );
    }

    /**
     * BC
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'booking_edit';
    }

    /**
     * JMS Translation messages
     *
     * @return array
     */
    public static function getTranslationMessages()
    {
        $messages = array();
        $messages[] = new Message(self::$tacError, 'cocorico');

        return $messages;
    }
}

src/Cocorico/CoreBundle/Form/Type/Dashboard/BookingStatusFilterType.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CoreBundle\Form\Type\Dashboard;

use Cocorico\CoreBundle\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingStatusFilterType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'status',
                'choice',
                array(
                    'mapped' => false,
                    /** @Ignore */
                    'label' => false,
                    'choices' => array_flip(Booking::getVisibleStatusValues()),
                    'empty_value' => 'admin.booking.status.label',
                    'translation_domain' => 'cocorico_booking',
                    'choices_as_values' => true
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults(
            array(
                'csrf_protection' => false,
                'translation_domain' => 'cocorico_booking',
            )
        );
    }

    /**
     * BC
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'booking_status_filter';
    }
}

src/Cocorico/CoreBundle/Form/Type/Dashboard/ListingEditAvailabilitiesStatusType.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CoreBundle\Form\Type\Dashboard;

use Cocorico\CoreBundle\Document\ListingAvailability;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ListingEditAvailabilitiesStatusType extends ListingEditAvailabilitiesType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder
            ->add(
                'status',
                'choice',
                array(
                    'label' => 'listing.form.status',
                    'mapped' => false,
                    'choices' => array_flip(ListingAvailability::$visibleValues),
                    'choices_as_values' => true
                )
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);
        $resolver->setDefaults(
            array(
                'translation_domain' => 'cocorico_listing',
            )
        );
    }

    /**
     * BC
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'listing_edit_availabilities_status';
    }
}

src/Cocorico/CoreBundle/Resources/views/Dashboard/Booking/_booking_index.html.twig
{% trans_default_domain 'cocorico_booking' %}

{% for booking in bookings.iterator %}

    {% if app.user == booking.user %} {#asker#}
        {% set other_user = booking.listing.user %}
        {% set booking_show_route = 'cocorico_dashboard_booking_show_asker' %}
        {% set amount_total = booking.amountToPayByAskerDecimal %}
        {% set other_user_rating = other_user.averageOffererRating %}
        {% set vat_inclusion_text = vatInclusionText(app.request.getLocale(), true, true ) %}
    {% elseif app.user == booking.listing.user %}{#offerer#}
        {% set other_user = booking.user %}
        {% set booking_show_route = 'cocorico_dashboard_booking_show_offerer' %}
        {% if includeVat %}
            {% set amount_total = booking.amountToPayToOffererDecimal %}
        {% else %}
            {% set amount_total = booking.amountToPayToOffererExcludingVATDecimal(vatRate) %}
        {% endif %}
        {% set vat_inclusion_text = vatInclusionText(app.request.getLocale()) %}

        {% set other_user_rating = other_user.averageAskerRating %}
    {% endif %}

    {% set user_image = other_user.images|length ? other_user.images[0].name : UserImageConstants.IMAGE_DEFAULT %}
    {% set listing = booking.listing %}
    {% set listing_translation = listing.translations[app.request.locale] %}
    {% set listing_image = listing.images|length ? listing.images[0].name : ListingImageConstants.IMAGE_DEFAULT %}

    {% set amount_total = amount_total | format_price(app.request.locale, 2) %}

    <!-- post -->
    <article class="post">
        <span class="hidden">{{ listing_translation.title }}</span>

        <div class="post-area">
            <div class="img-holder">
                <a href="{{ path('cocorico_listing_show', { 'slug': listing_translation.slug }) }}">
                    <img src="{{ (ListingImageConstants.IMAGE_FOLDER ~ listing_image) | imagine_filter('listing_xmedium') }}"
                         alt="{{ listing_translation.title }}">
                </a>
            </div>
            <div class="area">
                <header class="head">
                    <div class="area">
                        <h2>
                            <a href="{{ path('cocorico_listing_show', { 'slug': listing_translation.slug }) }}">
                                {{ listing_translation.title }}
                            </a>
                        </h2>
                    </div>
                    <div class="meta pull-right">
                        <span class="booking-info">
                            {{ 'booking.show.number.title'|trans }} :
                            <strong>
                                {{ booking.id }}
                            </strong>
                        </span>
                    </div>
                    {# <div class="booking-detail">
                          <ul class="list-inline" id="booking-asker-date">
                              <li content="{{ booking.start|date('Y-m-d') }}">
                                  {{ 'booking.show.start:'|trans }}
                                  <time>
                                      {{ booking.start|localizeddate('short', 'none', 'fr') }}
                                  </time>
                              </li>

                              <li>
                                  {{ 'booking.show.end:'|trans }}
                                  <time>
                                      {{ booking.end|localizeddate('short', 'none', 'fr') }}
                                  </time>
                              </li>

                              {% if not timeUnitIsDay %}
                                  <li>
                                      {{ 'booking.show.start_time:'|trans }}
                                      <time>
                                          {{ booking.startTime|date('H:i') }}
                                      </time>
                                  </li>
                                  <li>
                                      {{ 'booking.show.end_time:'|trans }}
                                      <time>
                                          {{ booking.endTime|date('H:i') }}
                                      </time>
                                  </li>
                              {% endif %}
                              <li class="booking-duration">
                                  <strong>
                                      {% set booking_duration = booking.duration(endDayIncluded, timeUnit) %}
                                      {{ 'booking.duration:'|trans }}
                                      <span class="normal-text">
                                          {{ booking_duration|add_time_unit_text }}
                                      </span>
                                  </strong>
                              </li>
                          </ul>
                      </div>   #}
                </header>
                <div class="post-content">
                    <div class="author-img">
                        <img src="{{ (UserImageConstants.IMAGE_FOLDER ~ user_image) | imagine_filter('user_xsmall') }}"
                             alt="{{ other_user.name }}">
                    </div>
                    <div class="textbox">
                        <span class="author-info">
                            <a href="{{ path('cocorico_user_profile_show', { 'id': other_user.id }) }}"><strong>{{ other_user.name }}</strong></a>
                        </span>
                        {% if other_user_rating %}
                            {{ other_user_rating|cocorico_star_rating }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer">
            <strong class="price">
                <span>
                    {{ amount_total }}
                    <sup>
                        <small>{{ vat_inclusion_text }}</small>
                    </sup>
                </span>
                <button title="{{ 'booking.amount_total.help'|trans }}" data-placement="right" data-toggle="tooltip"
                        class="tooltip-button" type="button">
                    ?
                </button>
            </strong>


            {% set status_class = bookingStatusClass[booking.status] %}
            <span class="btn {{ status_class }}">
                {{ 'booking.show.status.title'|trans }} {{ booking.statusText|trans }}
            </span>


            <a href="{{ path(booking_show_route, { 'id': booking.id}) }}" class="btn btn-default">
                {{ 'booking.index.show'|trans }}
            </a>

            {% set expiration = booking.getTimeBeforeExpiration(bookingExpirationDelay, bookingAcceptationDelay, timeZone) %}
            {% if expiration > 0 %}
                <strong class="expiry">
                    {{ 'booking.expire_in:'|trans }} {{ expiration|format_seconds }}
                </strong>
            {% endif %}
        </footer>
    </article>

{% endfor %}

src/Cocorico/CoreBundle/Resources/views/Dashboard/Booking/_booking_show.html.twig
{% trans_default_domain 'cocorico_booking' %}

{% set user_image = other_user.images|length ? other_user.images[0].name : UserImageConstants.IMAGE_DEFAULT %}
{% set listing = booking.listing %}
{% set listing_translation = listing.translations[app.request.locale] %}
{% set image = listing.images|length ? listing.images[0].name : ListingImageConstants.IMAGE_DEFAULT %}

{% set amount_total = amount_total | format_price(app.request.locale, 2) %}

<!-- post -->
<article class="post">
    <span class="hidden">{{ listing_translation.title }}</span>

    <div class="post-area">

        <div class="img-holder">
            <a href="{{ path('cocorico_listing_show', { 'slug': listing_translation.slug }) }}">
                <img src="{{ (ListingImageConstants.IMAGE_FOLDER ~ image) | imagine_filter('listing_xmedium') }}"
                     alt="{{ listing_translation.title }}">
            </a>
        </div>

        <div class="area">
            <header class="head">
                <div class="area">
                    <h2>
                        <a href="{{ path('cocorico_listing_show', { 'slug': listing_translation.slug }) }}">
                            {{ listing_translation.title }}
                        </a>
                    </h2>
                </div>

                <div class="meta">
                    <span class="booking-info">
                        {{ 'booking.show.number.title'|trans }} :
                        <strong>
                            {{ booking.id }}
                        </strong>
                    </span>
                </div>

                {# <div class="booking-detail">
                     <ul class="list-inline" id="booking-asker-date">
                         <li content="{{ booking.start|date('Y-m-d') }}">
                             {{ 'booking.show.start:'|trans }}
                             <time>
                                 {{ booking.start|localizeddate('short', 'none', 'fr') }}
                             </time>
                         </li>
                         <li>
                             {{ 'booking.show.end:'|trans }}
                             <time>
                                 {{ booking.end|localizeddate('short', 'none', 'fr') }}
                             </time>
                         </li>

                         {% if not timeUnitIsDay %}
                             <li>
                                 {{ 'booking.show.start_time:'|trans }}
                                 <time>
                                     {{ booking.startTime|date('H:i') }}
                                 </time>
                             </li>
                             <li>
                                 {{ 'booking.show.end_time:'|trans }}
                                 <time>
                                     {{ booking.endTime|date('H:i') }}
                                 </time>
                             </li>
                         {% endif %}
                     </ul>
                 </div>#}
            </header>

            <div class="post-content">
                <div class="author-img">
                    <img src="{{ (UserImageConstants.IMAGE_FOLDER ~ user_image) | imagine_filter('user_xsmall') }}"
                         alt="{{ other_user.name }}">
                </div>
                <div class="textbox">
                    <span class="author-info">
                        <a href="{{ path('cocorico_user_profile_show', { 'id': other_user.id }) }}"><strong>{{ other_user.name }}</strong></a>
                    </span>
                    {% if other_user_rating %}
                        {{ other_user_rating | cocorico_star_rating }}
                    {% endif %}
                </div>

                {% if bundleExist('CocoricoDeliveryBundle') %}
                    {% include 'CocoricoDeliveryBundle:Dashboard:Booking/_show_delivery.html.twig' with {
                    'booking': booking
                    } only %}
                {% elseif bundleExist('CocoricoCarrierBundle') %}
                    {% include 'CocoricoCarrierBundle:Dashboard:Booking/_show_carrier.html.twig' with {
                    'booking': booking
                    } only %}
                {% endif %}
            </div>

            {% if bundleExist('CocoricoListingOptionBundle') %}
                {% include 'CocoricoListingOptionBundle:Dashboard:Booking/_booking_show_options.html.twig' with {
                'booking': booking
                } only %}
            {% endif %}

        </div>
    </div>

    <footer class="footer">
        <strong class="price">
            <span data-id="booking-total">
                {{ amount_total }}
                <sup>
                    <small>{{ vat_inclusion_text }}</small>
                </sup>
            </span>
            <button title="{{ 'booking.amount_total.help'|trans }}" data-placement="right" data-toggle="tooltip"
                    class="tooltip-button" type="button">
                ?
            </button>
        </strong>

        {#<strong class="booking-duration">
            {% set booking_duration = booking.duration(endDayIncluded, timeUnit) %}
            {{ 'booking.duration:'|trans }}
            <span class="normal-text">
                {{ booking_duration|add_time_unit_text }}
            </span>
        </strong>#}

        {% set status_class = bookingStatusClass[booking.status] %}
        <span class="btn {{ status_class }}">
            {{ 'booking.show.status.title'|trans }} {{ booking.statusText|trans }}
        </span>

        {% set expiration = booking.getTimeBeforeExpiration(bookingExpirationDelay, bookingAcceptationDelay, timeZone) %}
        {% if expiration > 0 %}
            <strong class="expiry">
                {{ 'booking.expire_in:'|trans }} {{ expiration|format_seconds }}
            </strong>
        {% endif %}
    </footer>

</article>

src/Cocorico/CoreBundle/Resources/views/Dashboard/Booking/_booking_show_address_delivery.html.twig
{% set address_delivery = booking.userAddress %}

<strong class="title">{{ 'entity.user.type.delivery'|trans({}, 'cocorico_user') }}</strong>
<span>{{ address_delivery.address }}</span>
<span>{{ address_delivery.zip }}</span>
<span>
    {{ address_delivery.city }}
    {{ address_delivery.country | country_name(app.request.locale) }}
</span>

src/Cocorico/CoreBundle/Resources/views/Dashboard/Booking/_filters.html.twig
<!-- form-filter -->
{{ form_start(filterForm, { 'attr': {'class': 'form-filter' } }) }}
{{ form_widget(filterForm) }}
{{ form_end(filterForm) }}